# jekyll settings
permalink: pretty
exclude: [Gemfile, Gemfile.lock, Guardfile, README.md, CNAME, '*.scss']
excerpt_separator: "\n\n"
kramdown:
  syntax_highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-sitemap

title: Chen Yangjian
description: Everything about Chen Yangjian.
url: http://cyj.me
author:
  name: Chen Yangjian
  uri: http://cyj.me
feed:
  path: feed/atom.xml
