# jekyll settings
baseurl:
pygments: true
markdown: rdiscount
lsi: false
permalink: /:categories/:title
exclude: [Gemfile, Gemfile.lock, Guardfile, README.md, CNAME, '*.scss']
excerpt_separator: "\n\n"
