# jekyll settings
baseurl:
highlighter: pygments
lsi: false
permalink: /:categories/:title
exclude: [Gemfile, Gemfile.lock, Guardfile, README.md, CNAME, '*.scss']
excerpt_separator: "\n\n"
gems:
- jekyll-sitemap
- jekyll-redirect-from
